export const actionTypes = {
  GET_ALL_JOBS_FETCH: 'GET_ALL_JOBS_FETCH',
  GET_ALL_JOBS_SUCCESS: 'GET_ALL_JOBS_SUCCESS',
  GET_ALL_JOBS_ERROR: 'GET_ALL_JOBS_ERROR',
  JOB_SEARCH: 'JOB_SEARCH',
  CREATE_JOB: 'CREATE_JOB',
  DELETE_JOB_BY_ID: 'DELETE_JOB_BY_ID'
};
